# Generated by Django 5.2.7 on 2025-11-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('raqam', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'db_table': 'Avto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon_raqami', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('ism', models.CharField(blank=True, max_length=100, null=True)),
                ('familiya', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Mijoz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tashrif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(blank=True, null=True)),
                ('joriy_km', models.IntegerField(blank=True, null=True)),
                ('keyingi_km', models.IntegerField(blank=True, null=True)),
                ('keyingi_sana', models.DateField(blank=True, null=True)),
                ('xizmatlar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tashrif',
                'managed': False,
            },
        ),
    ]
